name: date_utils
description: A Dart library for manipulating DateTimes.
version: 0.2.1
homepage: https://github.com/apptreesoftware/date_utils

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  intl: ^0.20.2

dev_dependencies:
  test: ^1.25.15
